### ISSUE TITLE
hi,do you know coroutine 

### ISSUE THREAD

**Issue by dwxiayi** [vrogier/ocilib#102]
coroutine is user state thread；when dbserver is busy for data-search、commit or other things，dbclient can using other coroutine do something，the old coroutine will go on work when dbserver respond the require，so app can have a better perform， so i test oci is support coroutine 。
i using coroutine lib（https://github.com/Tencent/libco）；
i write a case in a thread，create many co（coroutine），when co is less than 21，everything is ok，but co is biger than 21，the process will be kill；i test connect by occi、ocilib（single connect and pool），the    result is same。
can you help me test coroutine ？ 
sorry for poor my English，thinks！

**Comment by dwxiayi** [comment]
`
void* insertData(void* data)
{
	ULog(eINFO, "enter %s", __FUNCTION__);
	co_enable_hook_sys();
	//co_disable_hook_sys();
	coData* coD = (coData*)data;
	try
	{
		Connection con(url2);
		Statement state(con);

		ULog(eERROR, "connect ok id %d", coD->id);
		char buffer[1024] = {};
		co_enable_hook_sys();

		for (size_t i = coD->start; i < coD->end; i++)
		{
			sprintf(buffer, "INSERT INTO ipsp_affirm_001 (TAB_ID) VALUES(%d)", i);

			state.Execute(buffer);

			con.Commit();
			//ULog(eERROR,"commit ok");
			insertOK++;
		}
	}
	catch (exception& e)
	{
		ULog(eERROR, "exception error:msg[%s]", e.what());
	}
	catch (...)
	{
		ULog(eERROR, "unknow exception");
	}
	coCount--;
	delete coD;
}

int main(int argc, char** argv)
{
	//cos
	if (argc < 3)
	{
		printf("usage:%s dbInsertCounts coCounts", argv[0]);
		return -1;
	}
	vector<stCoRoutine_t *> vecCo;
	vector<coData *> vecDa;
	try
	{
		co_init_curr_thread_env();
		co_disable_hook_sys();

		int coS = atoi(argv[2]);
		insertNum = atoi(argv[1]);
		coCount = coS;

		//init
		Environment::Initialize();

		stCoRoutineAttr_t coAttr;
		coAttr.stack_size = 1024 * 1024 * 1;//8M
		for (size_t i = 0; i < coS; i++)
		{
			stCoRoutine_t * co1 = NULL;
			coData* data = new coData;
			//vecDa.push_back(data);
			data->start = i * (insertNum / coS) + 1;
			data->end = data->start + (insertNum / coS);
			data->id = i;
			co_create(&co1, &coAttr, insertData, data);
			vecCo.push_back(co1);
			//printf("start co %d\n", i + 1);
			co_resume(co1);
		}

		co_eventloop(co_get_epoll_ct(), loop2, 0);
		ULog(eERROR, "insert end");
	}
	//catch (Exception& e)
	//{
	//	ULog(eERROR, "Exception error:code[%s] msg[%s]", e.codes(), e.what());
	//}
	catch (exception& e)
	{
		ULog(eERROR, "exception error:msg[%s]", e.what());
	}
	catch (...)
	{
		ULog(eERROR, "unknow exception");
	}
	for (int i = 0; i < vecCo.size(); ++i)
	{
		co_release(vecCo[i]);
	}

	Environment::Cleanup();

	printf("insert info %d\n", insertOK);
	return 0;
}
`

**Comment by dwxiayi** [comment]
`
Pool* g_pool = NULL;
void printfPool()
{
	printf("pool info\nmin:%d\nmax:%d\nbusy:%d\nconnects:%d\n\n"
		,g_pool->GetMinSize()
		,g_pool->GetMaxSize()
		,g_pool->GetBusyConnectionsCount()
		,g_pool->GetOpenedConnectionsCount()
		);	
}

void* insertDataPool(void* data)
{
	ULog(eINFO, "enter %s", __FUNCTION__);
	co_enable_hook_sys();
	co_disable_hook_sys();
	coData* coD = (coData*)data;
	try
	{
		Connection con = g_pool->GetConnection();
		//printfPool();
		//printfd();
		Statement state(con);

		ULog(eERROR, "connect ok id %d", coD->id);
		char buffer[1024] = {};
		co_enable_hook_sys();

		for (size_t i = coD->start; i < coD->end; i++)
		{
			sprintf(buffer, "INSERT INTO ipsp_affirm_001 (TAB_ID) VALUES(%d)", i);

			state.Execute(buffer);

			con.Commit();
			//ULog(eERROR,"commit ok");
			insertOK++;
		}
	}
	catch (exception& e)
	{
		ULog(eERROR, "exception error:msg[%s]", e.what());
	}
	catch (...)
	{
		ULog(eERROR, "unknow exception");
	}
	coCount--;
	delete coD;
}

int main(int argc, char** argv)
{
	//cos
	if (argc < 3)
	{
		printf("usage:%s dbInsert coCounts", argv[0]);
		return -1;
	}
	vector<stCoRoutine_t *> vecCo;

	try
	{
		printfd();
		co_init_curr_thread_env();
		co_disable_hook_sys();

		int coS = atoi(argv[2]);
		insertNum = atoi(argv[1]);
		coCount = coS;

		//init
		printfd();
		Environment::Initialize();
		Pool pool(url2, Pool::ConnectionPool, 0, 100);
		g_pool = &pool;
		stCoRoutineAttr_t coAttr;
		coAttr.stack_size = 1024 * 1024 * 1;//1M

		for (size_t i = 0; i < coS; i++)
		{
			stCoRoutine_t * co1 = NULL;
			coData* data = new coData;
			data->start = i * (insertNum / coS) + 1;
			data->end = data->start + (insertNum / coS);
			data->id = i;

			co_create(&co1, &coAttr, insertDataPool, data);
			vecCo.push_back(co1);
			co_resume(co1);
		}

		co_eventloop(co_get_epoll_ct(), loop2, 0);
		ULog(eERROR, "insert end");
	}
	//catch (Exception& e)
	//{
	//	ULog(eERROR, "Exception error:code[%s] msg[%s]", e.codes(), e.what());
	//}
	catch (exception& e)
	{
		ULog(eERROR, "exception error:msg[%s]", e.what());
	}
	catch (...)
	{
		ULog(eERROR, "unknow exception");
	}
	for (int i = 0; i < vecCo.size(); ++i)
	{
		co_release(vecCo[i]);
	}

	Environment::Cleanup();

	printf("insert info %d\n", insertOK);
	return 0;
}

`

**Comment by dwxiayi** [comment]
(gdb) bt
#0  0x00007ffff4eb1305 in slaac_int () from /home/develop/product/Linux64/opt/oracle.oci.Linux64/lib/libclntsh.so.12.1
#1  0x00007ffff4eb120f in slrac () from /home/develop/product/Linux64/opt/oracle.oci.Linux64/lib/libclntsh.so.12.1
#2  0x00007ffff3449cd8 in unw_is_signal_frame () from /home/develop/product/Linux64/opt/oracle.oci.Linux64/lib/libclntsh.so.12.1
#3  0x00007ffff343575a in skgdsgframe () from /home/develop/product/Linux64/opt/oracle.oci.Linux64/lib/libclntsh.so.12.1
#4  0x00007ffff32ebff8 in kgdsdsts_extra () from /home/develop/product/Linux64/opt/oracle.oci.Linux64/lib/libclntsh.so.12.1
#5  0x00007ffff32ebdfe in kgdsdsts () from /home/develop/product/Linux64/opt/oracle.oci.Linux64/lib/libclntsh.so.12.1
#6  0x00007ffff4b56484 in kpedbg_dmp_stack () from /home/develop/product/Linux64/opt/oracle.oci.Linux64/lib/libclntsh.so.12.1
#7  0x00007ffff4b566e2 in kpeDbgCrash () from /home/develop/product/Linux64/opt/oracle.oci.Linux64/lib/libclntsh.so.12.1
#8  0x00007ffff30a6303 in kpuauthxa () from /home/develop/product/Linux64/opt/oracle.oci.Linux64/lib/libclntsh.so.12.1
#9  0x00007ffff30a43aa in kpuauth () from /home/develop/product/Linux64/opt/oracle.oci.Linux64/lib/libclntsh.so.12.1
#10 0x00007ffff304555b in OCISessionBegin () from /home/develop/product/Linux64/opt/oracle.oci.Linux64/lib/libclntsh.so.12.1
#11 0x00007ffff6aec36a in OCI_ConnectionLogon (con=0xd30168, new_pwd=<optimized out>, tag=0x7ffff68c94b8 "") at connection.c:492
#12 0x00007ffff6aed59f in OCI_ConnectionCreateInternal (pool=<optimized out>, db=<optimized out>, user=<optimized out>, 
    pwd=<optimized out>, mode=<optimized out>, tag=0x7ffff68c94b8 "") at connection.c:53
#13 0x00007ffff6b01d64 in OCI_PoolGetConnection (pool=0x6b8888, tag=0x7ffff68c94b8 "") at pool.c:377
#14 0x00000000004141a5 in ocilib::Pool::GetConnection (this=0x7fffffffddb0, sessionTag=...)
    at ./ocilib/ocilib-4.3.3/include/ocilib_impl.hpp:1339
#15 0x0000000000404c7d in insertDataPool (data=0xd0e340) at ociTest.cpp:224
#16 0x00007ffff7277d60 in CoRoutineFunc (co=0xd2e030) at co_routine.cpp:448
#17 0x0000000000000000 in ?? ()
