### ISSUE TITLE
OCI_PoolSetNoWait doesn't work for offline database

### ISSUE THREAD

**Issue by zheltkov** [vrogier/ocilib#209]
Hello,
I'm using **ocilib v4.6.2**  to make Connection Pool to oracle database.
But if database is offline or network connectioin is lost then **OCI_Pool** will wait forever on calling 
**OCI_PoolGetConnection** even if  **OCI_PoolSetNoWait(pool, TRUE)**  was setup.

In attach there is example to reproduce.
[test_pool_nowait.c.txt](https://github.com/vrogier/ocilib/files/3311231/test_pool_nowait.c.txt)

```
> gcc test_pool_nowait.c -o test_pool -g -locilib -I/usr/include/ocilib
> gdb ./test_pool
> run
> Ctrl+C
> bt
```

**Comment by zheltkov** [comment]
```
#0  0x00007ffff7c50428 in __GI___poll (fds=0x7ffffffeae98, nfds=1, timeout=60000) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff425161f in sntpoltst () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#2  0x00007ffff4157b0b in ntctst () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#3  0x00007ffff421a0be in nttwait () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#4  0x00007ffff4216da0 in nttcni () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#5  0x00007ffff420cd0e in nttcon () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#6  0x00007ffff415785d in ntconn () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#7  0x00007ffff410d493 in nsopen () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#8  0x00007ffff40d8e9e in nscall1 () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#9  0x00007ffff40d6b2d in nscall () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#10 0x00007ffff416e4fe in niotns () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#11 0x00007ffff4179c69 in osncon () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#12 0x00007ffff400e0d9 in kpuadef () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#13 0x00007ffff3ff4e53 in upiini () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#14 0x00007ffff400ccbf in kpuatch () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#15 0x00007ffff4f84667 in kpusplockfreeatch () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#16 0x00007ffff4f7caf0 in kpuspextend () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#17 0x00007ffff4f7ea3c in kpuspgetfreesession () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#18 0x00007ffff4f7b9b5 in kpuspgetpooledsession () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#19 0x00007ffff4f778b1 in kpuspsessionget () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#20 0x00007ffff4cdae3c in OCISessionGet () from /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1
#21 0x00007ffff7d3f1ba in OCI_ConnectionLogonSessionPool (ctx=ctx@entry=0x7fffffffd6d0, con=con@entry=0x496718, tag=0x0) at connection.c:580
#22 0x00007ffff7d4085b in OCI_ConnectionLogon (con=con@entry=0x496718, new_pwd=new_pwd@entry=0x0, tag=tag@entry=0x0) at connection.c:647
#23 0x00007ffff7d413ff in OCI_ConnectionCreateInternal (pool=pool@entry=0x481028, db=<optimized out>, user=<optimized out>, pwd=<optimized out>, mode=<optimized out>, tag=0x0)
    at connection.c:930
#24 0x00007ffff7d5a803 in OCI_PoolGetConnection (pool=0x481028, tag=<optimized out>) at pool.c:386
#25 0x000000000040129e in main () at test_pool_nowait.c:71
```

**Comment by zheltkov** [comment]
Probably this is not a library issue, because parameter **(CONNECT_TIMEOUT=10)**  in **tnsnames.ora**  resolve that problem.
