### ISSUE TITLE
AddressSanitizer reports error in ManagedBuffer

### ISSUE THREAD

**Issue by bill-torpey** [vrogier/ocilib#262]
During test with AddressSanitizer ocilib triggers an error in ManagedBuffer:

```
==tpsworker==1188529==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete) on 0x61d000042e80
    #0 0x7f609d5a8025 in operator delete(void*, unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x111025)
    #1 0x7f609d45f4e9 in ocilib::core::ManagedBuffer<char>::~ManagedBuffer() /build/share/ocilib/4.7.2/include/ocilibcpp/detail/core/ManagedBuffer.hpp:47
    #2 0x7f609d45f4e9 in ocilib::Lob<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, 2>::Read(unsigned int) /build/share/ocilib/4.7.2/include/ocilibcpp/detail/Lob.hpp:54
    ...
0x61d000042e80 is located 0 bytes inside of 2055-byte region [0x61d000042e80,0x61d000043687)
allocated by thread T10 here:
    #0 0x7f609d5a6b47 in operator new[](unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10fb47)
    #1 0x7f609d4519b9 in ocilib::core::ManagedBuffer<char>::ManagedBuffer(unsigned long) /build/share/ocilib/4.7.2/include/ocilibcpp/detail/core/ManagedBuffer.hpp:40
    #2 0x7f609d45f34a in ocilib::Lob<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, 2>::Read(unsigned int) /build/share/ocilib/4.7.2/include/ocilibcpp/detail/Lob.hpp:54
    ...      
```

This was on Ubuntu 20.04 using clang 10 with ocilib 4.7.2.

**Comment by vrogier** [comment]
Hi,

Thanks for reporting the issue!
This will fixed.

Regards,

Vincent

**Comment by bill-torpey** [comment]
Thanks Vincent!  And thanks for a terrific project!

**Comment by bill-torpey** [comment]
Hi Vincent:

While regression testing this fix I found several other similar issues -- let me know if you'd like me to add to this issue or open a new one.  Thanks!

**Comment by vrogier** [comment]
Hi,

Create a new issue :) 

Thanks 👍 

Vincent
